
### root
GET {{base}}/
Accept: application/json


### check_mem_all

GET {{base}}/check_mem_all/available?unit=G
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### check_mem

GET {{base}}/check_mem/0?unit=G
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### txt2img

GET {{base}}/task/txt2img
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "params": {
    "prompt": "The sprirt of a Tamagotchi wandering in the city of Los Angeles",
    "negative_prompt": "",
    "seed": 0,
    "width": 1024,
    "height": 1024,
    "batch_size": 2,
    "prior_num_inference_steps": 20,
    "prior_guidance_scale": 4.0,
    "decoder_num_inference_steps": 10,
    "decoder_guidance_scale": 1.1
  },
  "launch": {
    "device_index": 6
  }
}


### img2img

GET {{base}}/task/img2img
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "params": {
    "image": "https://oss-prod.tishi.top/sd/t/SgNQaKyqnSHf2PVa/zDVycPK3VqCbvXJ3/1704119655_5.png",
    "prompt": "a cup of coffee",
    "negative_prompt": "",
    "seed": 0,
    "width": 1024,
    "height": 1024,
    "batch_size": 2,
    "prior_num_inference_steps": 20,
    "prior_guidance_scale": 4.0,
    "decoder_num_inference_steps": 10,
    "decoder_guidance_scale": 1.1
  },
  "launch": {
    "device_index": 6
  }
}


### img_variate

GET {{base}}/task/img_variate
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "params": {
    "image": "https://oss-prod.tishi.top/sd/t/SgNQaKyqnSHf2PVa/zDVycPK3VqCbvXJ3/1704119655_5.png",
    "prompt": "a cup of coffee",
    "negative_prompt": "",
    "seed": 0,
    "width": 1024,
    "height": 1024,
    "batch_size": 2,
    "prior_num_inference_steps": 20,
    "prior_guidance_scale": 4.0,
    "decoder_num_inference_steps": 10,
    "decoder_guidance_scale": 1.1
  },
  "launch": {
    "device_index": 6
  }
}

