
### root
GET {{base}}/
Accept: application/json


### check_mem_all

GET {{base}}/check_mem_all/available?unit=G
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### check_mem

GET {{base}}/check_mem/0?unit=G
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### txt2img

POST {{base}}/task/txt2img
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "prompt": "The sprirt of a Tamagotchi wandering in the city of Los Angeles",
    "negative_prompt": "",
    "seed": 0,
    "width": 1536,
    "height": 1536,
    "batch_size": 2,
    "steps": 20,
    "guidance_scale": 4.0,
    "steps2": 10,
    "guidance_scale2": 1.1
  },
  "launch": {
    "device_index": 3
  }
}


### img2img

POST {{base}}/task/img2img
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "image": "https://oss-prod.tishi.top/sd/t/SgNQaKyqnSHf2PVa/zDVycPK3VqCbvXJ3/1704119655_5.png",
    "prompt": "a cup of tea",
    "negative_prompt": "",
    "seed": 0,
    "width": 880,
    "height": 1024,
    "batch_size": 2,
    "steps": 20,
    "guidance_scale": 4.0,
    "steps2": 10,
    "guidance_scale2": 1.1
  },
  "launch": {
    "device_index": 2
  }
}


### img_variate

POST {{base}}/task/img_variate
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "image": "https://oss-prod.tishi.top/sd/t/SgNQaKyqnSHf2PVa/zDVycPK3VqCbvXJ3/1704119655_5.png",
    "prompt": "a cup of tea",
    "negative_prompt": "",
    "seed": 0,
    "width": 800,
    "height": 1024,
    "batch_size": 2,
    "steps": 20,
    "guidance_scale": 4.0,
    "steps2": 10,
    "guidance_scale2": 1.1
  },
  "launch": {
    "device_index": 2
  }
}

